name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Ini akan mencari agen di server Dalang Anda
    runs-on: self-hosted

    steps:
      - name: Pull latest code and Deploy
        run: |
          # Pindah ke direktori utama repo Anda
          cd ~/AgniRakhsa-FireDetection
          
          # Ambil update terbaru dari GitHub
          git fetch --all
          git reset --hard origin/main
          
          # Tulis file env di direktori yang benar
          echo "${{ secrets.WEB_ENV }}" > web/.env
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
          echo "${{ secrets.GATEWAY_ENV }}" > whatsapp-gateway/.env
          
          # Rebuild dan jalankan dockercompose
          docker compose up -d --build
