name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Ini akan mencari agen di server Dalang Anda
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Environment Files
        run: |
          echo "${{ secrets.WEB_ENV }}" > web/.env
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
          echo "${{ secrets.GATEWAY_ENV }}" > whatsapp-gateway/.env

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build
